name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run tests
      run: flutter test
      
    - name: Run analysis
      run: flutter analyze
      
    - name: Check formatting
      run: dart format --set-exit-if-changed .

  package-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run package analysis
      run: flutter pub deps
      
    - name: Check pub publish warnings
      run: flutter pub publish --dry-run
      
    - name: Install pana (package analyzer)
      run: flutter pub global activate pana
      
    - name: Run pana analysis
      run: flutter pub global run pana --no-warning --source path .

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run security audit
      run: flutter pub deps --style=compact | grep -E "(direct|transitive)" || true
      
    - name: Check for known vulnerabilities
      run: |
        # Check pubspec.lock for known vulnerable packages
        # This is a basic check - in production you might want to use more sophisticated tools
        if grep -q "some_vulnerable_package" pubspec.lock; then
          echo "Found vulnerable dependencies"
          exit 1
        fi