name: Golden Tests

on:
  push:
    branches: [ master ]
    paths: 
      - 'assets/**'
      - 'lib/**'
      - 'test/**'
      - 'tool/**'
  pull_request:
    branches: [ master, main ]
    paths: 
      - 'assets/**'
      - 'lib/**'
      - 'test/**'
      - 'tool/**'

jobs:
  golden-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.29.3'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Generate latest code
      run: dart tool/generate_logos_and_tests.dart
      
    - name: Run golden tests
      run: flutter test --update-goldens
      
    - name: Upload golden files as artifacts
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: golden-files
        path: test/goldens/
        
    - name: Check for golden file changes
      run: |
        if [ -n "$(git status --porcelain test/goldens)" ]; then
          echo "::error::Golden files have changed. Please update them locally and commit the changes."
          echo "Changed files:"
          git status test/goldens
          echo "Differences:"
          git diff test/goldens
          exit 1
        fi
