name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run tests
      run: flutter test
      
    - name: Analyze project source
      run: flutter analyze
      
    - name: Check formatting
      run: dart format --output=none --set-exit-if-changed .
      
    - name: Verify code generation is up to date
      run: |
        dart tool/generate_logos_and_tests.dart
        if [ -n "$(git status --porcelain lib/src/ test/)" ]; then
          echo "Generated code is out of sync. Please run 'dart tool/generate_logos_and_tests.dart' locally and commit the changes."
          exit 1
        fi
        
    - name: Publish to pub.dev
      uses: k-paxian/dart-package-publisher@v1.6
      with:
        credentialJson: ${{ secrets.CREDENTIAL_JSON }}
        flutter: true
        skipTests: true
        
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release
          - Updated SVG logos
          - Bug fixes and improvements
        draft: false
        prerelease: false
